export const imageData = [
  { src: "/image/CSS3.svg", name: "CSS" },
  { src: "/image/Docker.svg", name: "Docker" },
  { src: "/image/Git.svg", name: "Git" },
  { src: "/image/Graphql.svg", name: "GraphQL" },
  { src: "/image/HTML5.svg", name: "HTML" },
  { src: "/image/JavaScript.svg", name: "JavaScript" },
  { src: "/image/MongoDB.svg", name: "MongoDB" },
  { src: "/image/Next.js.svg", name: "Next.js" },
  { src: "/image/NGINX.svg", name: "NGINX" },
  { src: "/image/Node.js.svg", name: "Node.js" },
  { src: "/image/PostgresSQL.svg", name: "PostgresSQL" },
  { src: "/image/React.svg", name: "React" },
  { src: "/image/Redis.svg", name: "Redis" },
  { src: "/image/Socket.io.svg", name: "Socket.io" },
  { src: "/image/Tailwind CSS.svg", name: "Tailwind CSS" },
  { src: "/image/TypeScript.svg", name: "TypeScript" },
];
